#ifndef __LIBMAPIADMIN_PROTO_H__
#define __LIBMAPIADMIN_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)

#ifndef __BEGIN_DECLS
#ifdef __cplusplus
#define __BEGIN_DECLS		extern "C" {
#define __END_DECLS		}
#else
#define __BEGIN_DECLS
#define __END_DECLS
#endif
#endif

__BEGIN_DECLS

/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

/* this file contains prototypes for functions that are part of 
 * the public API of this subsystem or library. */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif

_PUBLIC_ struct mapiadmin_ctx *mapiadmin_init(struct mapi_session *);
_PUBLIC_ enum MAPISTATUS mapiadmin_release(struct mapiadmin_ctx *);
_PUBLIC_ enum MAPISTATUS mapiadmin_user_extend(struct mapiadmin_ctx *);
_PUBLIC_ enum MAPISTATUS mapiadmin_user_add(struct mapiadmin_ctx *);
_PUBLIC_ enum MAPISTATUS mapiadmin_user_del(struct mapiadmin_ctx *);
_PUBLIC_ enum MAPISTATUS mapiadmin_user_mod(struct mapiadmin_ctx *);

__END_DECLS

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIBMAPIADMIN_PROTO_H__ */

