#ifndef __TORTURE_TORTURE_PROTO_H__
#define __TORTURE_TORTURE_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)

#ifndef __BEGIN_DECLS
#ifdef __cplusplus
#define __BEGIN_DECLS		extern "C" {
#define __END_DECLS		}
#else
#define __BEGIN_DECLS
#define __END_DECLS
#endif
#endif

__BEGIN_DECLS

/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from torture/mapi_restrictions.c  */

bool torture_create_environment(struct loadparm_context *,				TALLOC_CTX *mem_ctx, 
				mapi_object_t *parent,
mapi_object_t *);
bool torture_rpc_mapi_restrictions(struct torture_context *);

/* The following definitions come from torture/mapi_criteria.c  */

bool torture_rpc_mapi_criteria(struct torture_context *);

/* The following definitions come from torture/mapi_deletemail.c  */

bool torture_rpc_mapi_deletemail(struct torture_context *);

/* The following definitions come from torture/mapi_newmail.c  */

bool torture_rpc_mapi_newmail(struct torture_context *);

/* The following definitions come from torture/mapi_fetchmail.c  */

bool torture_rpc_mapi_fetchmail(struct torture_context *);

/* The following definitions come from torture/mapi_sendattach.c  */

bool torture_rpc_mapi_sendattach(struct torture_context *);

/* The following definitions come from torture/mapi_sorttable.c  */

bool torture_rpc_mapi_sorttable(struct torture_context *);

/* The following definitions come from torture/mapi_bookmark.c  */

bool torture_rpc_mapi_bookmark(struct torture_context *);

/* The following definitions come from torture/mapi_copymail.c  */

bool torture_rpc_mapi_copymail(struct torture_context *);

/* The following definitions come from torture/mapi_fetchattach.c  */

bool torture_rpc_mapi_fetchattach(struct torture_context *);

/* The following definitions come from torture/mapi_sendmail.c  */

bool torture_rpc_mapi_sendmail(struct torture_context *);

/* The following definitions come from torture/mapi_sendmail_html.c  */

bool torture_rpc_mapi_sendmail_html(struct torture_context *);

/* The following definitions come from torture/nspi_profile.c  */

bool set_profile_attribute(const char *, struct SRowSet, uint32_t, const char *);
bool set_profile_mvstr_attribute(const char *, struct SRowSet,uint32_t, const char *);
bool torture_rpc_nspi_profile(struct torture_context *);

/* The following definitions come from torture/nspi_resolvenames.c  */

bool torture_rpc_nspi_resolvenames(struct torture_context *);

/* The following definitions come from torture/mapi_fetchappointment.c  */

bool torture_rpc_mapi_fetchappointment(struct torture_context *);

/* The following definitions come from torture/mapi_sendappointment.c  */

bool torture_rpc_mapi_sendappointment(struct torture_context *);

/* The following definitions come from torture/mapi_fetchcontacts.c  */

bool torture_rpc_mapi_fetchcontacts(struct torture_context *);

/* The following definitions come from torture/mapi_sendcontacts.c  */

bool torture_rpc_mapi_sendcontacts(struct torture_context *);

/* The following definitions come from torture/mapi_fetchtasks.c  */

bool torture_rpc_mapi_fetchtasks(struct torture_context *);

/* The following definitions come from torture/mapi_sendtasks.c  */

bool torture_rpc_mapi_sendtasks(struct torture_context *);

/* The following definitions come from torture/mapi_common.c  */

const char *get_filename(const char *);
const char **get_cmdline_recipients(TALLOC_CTX *, const char *);
const char **collapse_recipients(TALLOC_CTX *, const char **, const char **, const char **);
bool set_usernames_RecipientType(TALLOC_CTX *, uint32_t *, struct SRowSet *, 					const char **usernames, struct SPropTagArray *flaglist,
enum ulRecipClass);
enum MAPISTATUS torture_load_profile(TALLOC_CTX *, 				     struct loadparm_context *lp_ctx,
struct mapi_session **);
struct mapi_session *torture_init_mapi(TALLOC_CTX *, struct loadparm_context *);
enum MAPISTATUS torture_simplemail_fromme(struct loadparm_context *,					  mapi_object_t *obj_parent, 
					  const char *subject, const char *body,
uint32_t);
uint32_t get_permission_from_name(const char *);

/* The following definitions come from torture/mapi_permissions.c  */

bool torture_rpc_mapi_permissions(struct torture_context *);

/* The following definitions come from torture/mapi_namedprops.c  */

bool torture_rpc_mapi_namedprops(struct torture_context *);

/* The following definitions come from torture/mapi_recipient.c  */

bool torture_rpc_mapi_recipient(struct torture_context *);

/* The following definitions come from torture/mapi_createuser.c  */

bool torture_mapi_createuser(struct torture_context *);

/* The following definitions come from torture/exchange_createuser.c  */

NTSTATUS torture_exchange_createuser(TALLOC_CTX *, const char *,const struct dom_sid *);
const struct dom_sid *torture_join_user_sid(struct test_join *);
struct test_join *torture_create_testuser(struct torture_context *,					  const char *username, 
					  const char *domain,
					  uint16_t acct_type,
const char **);
_PUBLIC_ void torture_leave_domain(struct test_join *);

/* The following definitions come from torture/openchange.c  */

NTSTATUS samba_init_module(void);
NTSTATUS torture_rpc_binding(struct torture_context *,struct dcerpc_binding **);
_PUBLIC_ NTSTATUS torture_rpc_connection(struct torture_context *,				struct dcerpc_pipe **p,
const struct ndr_interface_table *);

__END_DECLS

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __TORTURE_TORTURE_PROTO_H__ */

